### ISSUE TITLE
Is the correlation module here the same as IRR?

### ISSUE THREAD

**Issue by yzfly** [lliuz/ARFlow#1]
Is the correlation module here the same as [IRR](https://github.com/visinf/irr/tree/master/models)?

I have created environment for IRR and can run the code smoothly, so I want to know:

if I have install correlation module follow the IRR's instruction, can I use it for ARFlow too?

**Comment by lliuz** [comment]
Yes, it is the same as the one in IRR, PWC-Net or others.

**Comment by yzfly** [comment]
Thank you
