### ISSUE TITLE
what are these files in configs/root_sintel and root_sintel_raw?

### ISSUE THREAD

**Issue by RokiaAbdeen** [lliuz/ARFlow#12]
the first one might be the dataset path, what is the second?

**Comment by lliuz** [comment]
The first the root path for the official Sintel dataset, and the second is the root path for our Sintel raw dataset which is made by extracted all frames from the raw movie and manually group frames by shots for pre-training,

**Comment by RokiaAbdeen** [comment]
could you provide me the link for your sintel raw dataset please ?
