### ISSUE TITLE
utils.flow_utils ==> flow_to image 

### ISSUE THREAD

**Issue by RokiaAbdeen** [lliuz/ARFlow#16]
the output flow of kitti dataset is with only one color , what is the wrong?
![33](https://user-images.githubusercontent.com/26867350/97773638-7fe4bb00-1b8c-11eb-99d7-9c573b353b0d.png)

**Comment by RokiaAbdeen** [comment]
![Uploading 33.png…]()

**Comment by RokiaAbdeen** [comment]
this is the flow of kitti image, I used your pretrained model and mine and both are same, kitti gives me one color for whole flow image and sintel gaves me white flow

**Comment by lliuz** [comment]
Can you provide more details, such as the image names and some code snippets, so that I can reproduce your problem?

**Comment by lliuz** [comment]
I'm not sure if the cause of the problem is the same as #15, if you are using pytorch >= 1.3.0, please pull the latest code, and tell me if the problem still exists.

**Comment by RokiaAbdeen** [comment]
![k1](https://user-images.githubusercontent.com/26867350/99139562-d49c3180-2674-11eb-88f6-938d16348611.png)

**Comment by RokiaAbdeen** [comment]
![k2](https://user-images.githubusercontent.com/26867350/99139534-796a3f00-2674-11eb-935f-44862f68ec7c.png)

**Comment by RokiaAbdeen** [comment]
here is it, the complete inference code, with torch==1.1.0

**Comment by lliuz** [comment]
You used images from the left and right view at the same time, `_10` in the filename means the first frame for a pair of frames, `image_2` means left view, `image_3` means right view in KITTI dataset.
So all pixels are just moving to left with blue in visualization.

**Comment by RokiaAbdeen** [comment]
oh I understand, so to select two consecutive frames , I should use both of them from one folder , image_2 or image_3, right?

**Comment by lliuz** [comment]
yes

**Comment by RokiaAbdeen** [comment]
thanks so much for your answers
