### ISSUE TITLE
the aumented U12 formulation

### ISSUE THREAD

**Issue by zyl1336110861** [lliuz/ARFlow#18]
@lliuz 
Hello, Sir. Thanks for your sharing. When I read your paper, I find the following formula is hard to understand for me. I want to know **whether the tao_theta in the second formula should be the inverse of tao_theta**? Thank you very much!
![image](https://user-images.githubusercontent.com/49873271/99235816-4de08380-2831-11eb-96b8-90005fbab18a.png)

**Comment by lliuz** [comment]
yes, thanks for pointing it out this mistake and I will revise it in arxiv.
and the code is correct, you can refer to #4
