### ISSUE TITLE
Training question

### ISSUE THREAD

**Issue by soulslicer** [lliuz/ARFlow#2]
How can one use this code to train with the KITTI dataset?

Also where can I find the sintel_raw.json file etc. I downloaded the sintel dataset but i cannot find the json files

**Comment by lliuz** [comment]
Hi, @soulslicer 

You can find `sintel_raw.jon` in the [configs folder](https://github.com/lliuz/ARFlow/tree/master/configs). It should be noted that the *.json files in this repo are used to record the configurations of training.

Besides, training for KITTI is almost the same as the one for Sintel dataset, you can refer to the files for Sintel to implement it. If you have any problem please let me know :)

**Comment by soulslicer** [comment]
Ok
