### ISSUE TITLE
how to inference your given model on a set of consecutive images?

### ISSUE THREAD

**Issue by TengFeiHan0** [lliuz/ARFlow#6]
I 'd like to test your models on my own images, but each time it only accepts three images. will you support this option?

**Comment by lliuz** [comment]
Hi, @TengFeiHan0 
It is quite easy to implement it by yourself, here are some suggestions:

You can refer to [inference.py](https://github.com/lliuz/ARFlow/blob/master/inference.py) to implement it, just traverse your image samples and feed to the model to run repeatedly.

Besides, if you have a large number of consequent images, you can modify [the model file](https://github.com/lliuz/ARFlow/blob/master/models/pwclite.py#L258) to keep a buffer to save the feature pyramid of the previous image to save some inference time.
