### ISSUE TITLE
有关kitti数据集输入图像尺寸的问题(Questions about the size of the input image of the kitti dataset)

### ISSUE THREAD

**Issue by fupiao1998** [lliuz/ARFlow#7]
您好，感谢您开源的完备的代码，最近在研究您代码的时候发现在kitti的训练过程中将图像resize到了256×832的尺寸，想问您这样做的优势在于什么，如果在原始分辨率下进行实验的话会对精度有较大的影响吗。期待您的回答，谢谢！
Hello, thank you for the open source complete code. Recently, when researching your code, I found that during the training process of kitti, I resized the image to a size of 256×832. I want to ask you what is the advantage of doing this. If it is at the original resolution Does the experiment have a greater impact on accuracy? Looking forward to your answer

**Comment by lliuz** [comment]
一般图像大小越大精度越好。resize 到 256x832 是在训练速度和精度上的一个取舍,  但事实上更大或更小的图像大小也不会有特别明显的影响 (由于我没有特别注意上下采样的padding, 目前只能使用 64 的倍数的图像大小)

**Comment by MaoYuxin25** [comment]
好的，谢谢您的及时解答
