### ISSUE TITLE
SP parameters

### ISSUE THREAD

**Issue by hqqxyy** [lliuz/ARFlow#8]
ARFlow is a great job. I learn a lot from it.

I want to know that the parameter in 

Sintel_ft_ar.json : line 61
"rotate": [-0.2, 0.2, -0.015, 0.015]

and sp_transfroms.py: line 229
phi.uniform_(-min_rotate, max_rotate)

So the rotation is always 0,2 or 0.015. Why not set it as a random number like "trans" or "zoom"?

**Comment by lliuz** [comment]
It seems like a bug, and the correct one should be `phi.uniform_(min_rotate, max_rotate)`

Thanks for you pointing it out, I will test random rotation and update the results.

**Comment by lliuz** [comment]
Sorry for the late reply. I have tested the correct one and the results are almost unchanged. You can re-open this issue if there are any other problems :)

**Comment by hqqxyy** [comment]
Many thanks for your update! 

Btw, I am working on adapting ARFlow to my work. I noticed that the parameters of the second transformation are quite small, e.g. 0.015 vs 0.2. I want to know why not set it larger as it can introduce much more noise. Because I only have a few GPUs, I could not test it. Would you mind giving me some hints about it?  

Thanks.
